name: ai_model_server
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pytorch=2.4.0
  - torchvision=0.19.0
  - pyyaml
  - pip
  - pip:
    - transformers
    - fastapi==0.112.2
    - pycryptodomex==3.20.0
    - pydantic==2.8.2
    - pydantic_core==2.20.1
    - uvicorn
    - requests
    - aiohttp
    - colorlog
    - psutil
    - accelerate
    - bitsandbytes
    - av