inputs:
  - image_path
  - threshold
  - return_confidence
  - skipped_categories
output: result
short_name: dynamic_image
version: 1.0

models:
  - name: dynamic_image_ai
    inputs:
      - image_path
      - threshold
      - return_confidence
      - skipped_categories
    outputs:
      - result_early
  - name: image_result_postprocessor
    inputs:
      - result_early
    outputs:
      - result